import type { IncomingMessage, ServerResponse } from 'node:http';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { z } from 'zod';
import {
  createItineraryTool,
  getItineraryStatusTool,
  getItineraryTool,
  modifyItineraryTool,
  listUserTripsTool,
  saveItineraryTool,
  deleteTripTool,
  generatePackingListTool,
  askTravelExpertTool,
  getWeatherInsightsTool,
  estimateTripCostTool,
  searchGuidesTool,
  getTourAvailabilityTool,
  submitTourInquiryTool
} from './tools.js';

export const MCP_PATH = '/api/mcp';

export const SERVER_INFO = {
  name: 'plantrip-mcp-server',
  title: 'PlanTrip Travel MCP (sample data)',
  version: '2.0.0'
};

export const SOURCES = {
  sample: 'Sample data generated by this app (illustrative, not live)',
  plantrip: 'PlanTrip agent API (plantrip.io)'
} as const;

export const DATA_NOTICE =
  'Sample data: itineraries, costs, weather, guides and tours are illustrative values generated by this app, not live prices, forecasts or bookings. ' +
  'create_itinerary uses the PlanTrip API only when PLANTRIP_API_KEY is set and the API answers. ' +
  'Saved trips live in server memory, which is not shared between serverless instances.';

const text = (max: number) => z.string().trim().min(1).max(max);

const READ_ONLY = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false };
const WRITES_MEMORY = { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false };

type ToolDef = {
  name: string;
  title: string;
  description: string;
  inputSchema: z.ZodRawShape;
  annotations: typeof READ_ONLY;
  handler: (args: any) => Promise<any>;
};

export const TOOL_DEFS: ToolDef[] = [
  {
    name: 'create_itinerary',
    title: 'Create itinerary',
    description:
      'Returns a day-by-day itinerary with activities, estimated costs and local tips for a destination. ' +
      'Uses the PlanTrip API when this deployment has a PlanTrip key, otherwise generates a sample itinerary; the result says which. ' +
      'Does not book anything.',
    inputSchema: {
      destination: text(200).describe('Travel destination, e.g. "Kyoto, Japan"'),
      duration_days: z.number().int().min(1).max(14).optional().describe('Trip length in days, 1-14 (default 4)'),
      start_date: z.string().optional().describe('Start date in YYYY-MM-DD format'),
      budget: z.enum(['budget', 'moderate', 'luxury']).optional().describe('Budget category'),
      travel_style: z.enum(['cultural', 'foodie', 'adventure', 'relaxed', 'family', 'romantic', 'solo']).optional().describe('Style of travel'),
      travelers: z.number().int().min(1).max(20).optional().describe('Number of travelers'),
      interests: z.array(z.string()).optional().describe('Interests such as temples, food, photography'),
      notes: z.string().max(1000).optional().describe('Custom preferences or dietary constraints')
    },
    annotations: { ...WRITES_MEMORY, openWorldHint: true },
    handler: createItineraryTool
  },
  {
    name: 'get_itinerary_status',
    title: 'Get itinerary status',
    description:
      'Returns the generation status of an itinerary created on this server instance. ' +
      'Returns not found for unknown ids.',
    inputSchema: { itinerary_id: text(200).describe('Id returned by create_itinerary') },
    annotations: READ_ONLY,
    handler: getItineraryStatusTool
  },
  {
    name: 'get_itinerary',
    title: 'Get itinerary',
    description:
      'Returns the full itinerary with the given id from server memory. ' +
      'Returns not found when this server instance does not hold it; it never substitutes another trip.',
    inputSchema: { itinerary_id: text(200).describe('Itinerary id') },
    annotations: READ_ONLY,
    handler: getItineraryTool
  },
  {
    name: 'modify_itinerary',
    title: 'Modify itinerary',
    description:
      'Applies a natural-language change (more food stops, slower pace, sunset views) to an itinerary and returns the updated version. ' +
      'Pass the itinerary object too, because serverless instances do not share memory.',
    inputSchema: {
      itinerary_id: text(200).describe('Id of the itinerary to change'),
      modification_request: text(500).describe('Requested change, e.g. "Add more ramen spots on day 2"'),
      itinerary: z.any().optional().describe('The current itinerary object, used when the server does not hold it')
    },
    annotations: WRITES_MEMORY,
    handler: modifyItineraryTool
  },
  {
    name: 'list_user_trips',
    title: 'List saved trips',
    description:
      'Lists trips saved in this server instance\'s memory, including one sample Kyoto trip. ' +
      'Memory is not shared between serverless instances, so the browser also keeps its own copy.',
    inputSchema: {},
    annotations: READ_ONLY,
    handler: listUserTripsTool
  },
  {
    name: 'save_itinerary',
    title: 'Save itinerary',
    description: 'Stores an itinerary in server memory and returns its trip id. Nothing is written to a database.',
    inputSchema: {
      itinerary: z.any().describe('The itinerary object to save'),
      title: z.string().max(200).optional().describe('Optional custom title')
    },
    annotations: WRITES_MEMORY,
    handler: saveItineraryTool
  },
  {
    name: 'delete_trip',
    title: 'Delete trip',
    description: 'Removes a trip from server memory. Returns not found when this instance does not hold it.',
    inputSchema: { trip_id: text(200).describe('Id of the trip to delete') },
    annotations: { ...WRITES_MEMORY, destructiveHint: true, idempotentHint: true },
    handler: deleteTripTool
  },
  {
    name: 'generate_packing_list',
    title: 'Generate packing list',
    description:
      'Returns a sample packing checklist by category for a destination, trip length and season. ' +
      'Items are generated by this app from simple rules, not from a live forecast.',
    inputSchema: {
      destination: text(200).describe('Travel destination'),
      duration_days: z.number().int().min(1).max(60).optional().describe('Length of stay in days'),
      season_or_month: z.string().max(50).optional().describe('Season or month of travel'),
      activities: z.array(z.string()).optional().describe('Planned activities, e.g. hiking, fine dining'),
      travelers_type: z.string().max(100).optional().describe('Travel party, e.g. family with kids')
    },
    annotations: READ_ONLY,
    handler: generatePackingListTool
  },
  {
    name: 'ask_travel_expert',
    title: 'Ask travel expert',
    description:
      'Returns sample travel advice and key takeaways for a question about a destination (etiquette, transit, scams). ' +
      'Answers come from built-in templates, not a live source.',
    inputSchema: {
      question: text(500).describe('The travel question'),
      destination: text(200).describe('Destination city or region'),
      travel_context: z.string().max(500).optional().describe('Extra context, e.g. traveling with kids')
    },
    annotations: READ_ONLY,
    handler: askTravelExpertTool
  },
  {
    name: 'get_weather_insights',
    title: 'Get weather insights',
    description:
      'Returns sample climate figures (average highs, rain chance) and clothing advice for a destination and month. ' +
      'Values are illustrative, not a forecast.',
    inputSchema: {
      destination: text(200).describe('Destination'),
      month: z.union([z.string(), z.number()]).optional().describe('Month name or number')
    },
    annotations: READ_ONLY,
    handler: getWeatherInsightsTool
  },
  {
    name: 'estimate_trip_cost',
    title: 'Estimate trip cost',
    description:
      'Returns a sample budget breakdown (accommodation, food, transport, activities) for a destination. ' +
      'Prices are illustrative, not live quotes.',
    inputSchema: {
      destination: text(200).describe('Destination'),
      duration_days: z.number().int().min(1).max(60).optional().describe('Trip length in days'),
      travel_style: z.enum(['budget', 'moderate', 'luxury']).optional().describe('Comfort tier'),
      travelers: z.number().int().min(1).max(20).optional().describe('Number of travelers')
    },
    annotations: READ_ONLY,
    handler: estimateTripCostTool
  },
  {
    name: 'search_guides',
    title: 'Search guides',
    description: 'Returns sample travel guide articles filtered by query, destination and category. An empty list is a valid answer.',
    inputSchema: {
      query: z.string().max(200).optional().describe('Search words'),
      destination: z.string().max(200).optional().describe('Destination filter'),
      category: z.string().max(100).optional().describe('Category: culture, food, transport, practical')
    },
    annotations: READ_ONLY,
    handler: searchGuidesTool
  },
  {
    name: 'get_tour_availability',
    title: 'Get tour availability',
    description: 'Returns sample guided tours and date slots for a destination. Availability is illustrative, not live.',
    inputSchema: {
      destination: z.string().max(200).optional().describe('Destination filter'),
      tour_type: z.string().max(100).optional().describe('Type or theme of tour'),
      date: z.string().optional().describe('Target date in YYYY-MM-DD')
    },
    annotations: READ_ONLY,
    handler: getTourAvailabilityTool
  },
  {
    name: 'submit_tour_inquiry',
    title: 'Submit tour inquiry (demo)',
    description: 'Returns a demo inquiry reference for a tour. It does not book the tour, contact an operator or send email.',
    inputSchema: {
      tour_id: z.string().max(200).optional().describe('Tour id'),
      tour_title: z.string().max(200).optional().describe('Tour title'),
      destination: z.string().max(200).optional().describe('Destination city'),
      traveler_name: text(200).describe('Primary traveler name'),
      email: text(200).describe('Contact email address'),
      preferred_date: text(50).describe('Preferred tour date'),
      travelers_count: z.number().int().min(1).max(50).describe('Number of participants'),
      special_requests: z.string().max(1000).optional().describe('Dietary or accessibility notes')
    },
    annotations: WRITES_MEMORY,
    handler: submitTourInquiryTool
  }
];

// Direct handlers for in-process callers such as /api/chat
export const MCP_TOOLS_REGISTRY: Record<string, (args: any) => Promise<any>> = Object.fromEntries(
  TOOL_DEFS.map((t) => [t.name, t.handler])
);

export const MCP_TOOLS_METADATA = TOOL_DEFS.map((t) => ({ name: t.name, description: t.description }));

export function createMcpServer(): McpServer {
  const server = new McpServer(SERVER_INFO, { instructions: DATA_NOTICE });

  for (const tool of TOOL_DEFS) {
    server.registerTool(
      tool.name,
      {
        title: tool.title,
        description: tool.description,
        inputSchema: tool.inputSchema,
        annotations: tool.annotations
      },
      async (args: any) => {
        const result = await tool.handler(args);

        if (result && result.found === false) {
          const payload = { found: false, source: SOURCES.sample, message: result.message || `${tool.name}: nothing found.` };
          return {
            isError: true,
            content: [
              { type: 'text' as const, text: payload.message },
              { type: 'text' as const, text: JSON.stringify(payload) }
            ],
            structuredContent: payload
          };
        }

        const source = result?.source === 'plantrip-api' ? SOURCES.plantrip : SOURCES.sample;
        const payload = { found: true, source, result };
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(payload) }],
          structuredContent: payload
        };
      }
    );
  }

  return server;
}

function sendJson(res: ServerResponse, status: number, body: unknown, headers: Record<string, string> = {}) {
  res.writeHead(status, { 'Content-Type': 'application/json', ...headers });
  res.end(JSON.stringify(body));
}

function rpcError(code: number, message: string) {
  return { jsonrpc: '2.0', error: { code, message }, id: null };
}

function firstHeader(value: string | string[] | undefined): string | undefined {
  const v = Array.isArray(value) ? value[0] : value;
  return v?.split(',')[0]?.trim() || undefined;
}

/**
 * Streamable HTTP MCP endpoint. Stateless: a fresh server and transport per request,
 * so it runs the same under Express and as a Vercel function.
 */
export async function mcpHandler(req: IncomingMessage & { body?: unknown }, res: ServerResponse) {
  // Block cross-site browser calls (DNS rebinding); non-browser clients send no Origin.
  const origin = firstHeader(req.headers.origin);
  if (origin) {
    let originHost = '';
    try {
      originHost = new URL(origin).host;
    } catch {
      /* invalid origin -> rejected below */
    }
    const allowed = [firstHeader(req.headers.host), firstHeader(req.headers['x-forwarded-host'])].filter(Boolean);
    if (!allowed.includes(originHost)) {
      return sendJson(res, 403, rpcError(-32000, 'Forbidden: cross-origin requests are not allowed.'));
    }
  }

  if (req.method === 'GET' && !String(req.headers.accept || '').includes('text/event-stream')) {
    return sendJson(res, 200, {
      server: SERVER_INFO,
      tools: TOOL_DEFS.map((t) => t.name),
      data: DATA_NOTICE,
      connect: {
        transport: 'streamable-http',
        url: MCP_PATH,
        method: 'POST',
        accept: 'application/json, text/event-stream',
        auth: 'none'
      }
    });
  }

  if (req.method !== 'POST') {
    return sendJson(res, 405, rpcError(-32000, 'Method not allowed. Send MCP messages with POST.'), { Allow: 'POST, GET' });
  }

  let body: unknown;
  try {
    body = req.body;
  } catch {
    return sendJson(res, 400, rpcError(-32700, 'Parse error: request body is not valid JSON.'));
  }

  const server = createMcpServer();
  const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined, enableJsonResponse: true });
  res.on('close', () => {
    transport.close().catch(() => {});
    server.close().catch(() => {});
  });

  try {
    await server.connect(transport);
    await transport.handleRequest(req, res, body);
  } catch (err: any) {
    console.error('MCP request failed:', err?.message);
    if (!res.headersSent) sendJson(res, 500, rpcError(-32603, 'Internal server error'));
  }
}
